import type { Metadata } from "next";

import Container from "../components/Container";
import Header from "../components/Header";
import Footer from "../components/footer";
import "./globals.css";
// Defini este layout raiz para centralizar a estrutura visual comum a todas as páginas,
// evitando repetição de Container, Header e Footer individualmente.
// Isso garante consistência no layout, facilita manutenção e permite alterar
// a estrutura global da aplicação em um único ponto.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="Pt-Br">
      <body>
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
